//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACarA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int RentalID { get; set; }
        public int CustomerID { get; set; }
        public int VehicleID { get; set; }
        public int UserID { get; set; }
        public string RentNote { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateBack { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Vehicles Vehicles { get; set; }
    }
}
